ci-cd

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -25,4 +25,29 @@ jobs:
             git config --global user.name ${{ secrets.USERNAME }}
             git pull origin main
             git status
+
+  copy:
+    runs-on: ubuntu-latest
+    needs: deploy
+    steps:
+      - name: Deploy using ssh
+        uses: appleboy/ssh-action@v0.1.7
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.ADMINNAME }}
+          key: ${{ secrets.PRIVATE_KEY }}
+          port: 22
+          script: |
             cd PetWeb
+            npm generateFiles.js
+            mv html /var/www/html
+            mv images /var/www/images
+            mv nginx.conf /etc/nginx/nginx.conf
+            if sudo nginx -t; then
+              echo "Nginx configuration test passed, reloading..."
+              sudo systemctl reload nginx
+              echo "Nginx reloaded successfully"
+            else
+              echo "Nginx configuration test failed!"
+              exit 1
+            fi
